### ISSUE TITLE
Edit services

### ISSUE THREAD

**Issue by TayKangSheng** [wdi-sg/project-3-das#14]
I can edit services as a normal user?? Sorry i updated the photo just to test..

<img width="522" alt="screen shot 2017-03-16 at 11 02 23 am" src="https://cloud.githubusercontent.com/assets/10722197/23980030/24187a3c-0a38-11e7-8990-37ee1a57cf1b.png">
<img width="526" alt="screen shot 2017-03-16 at 11 02 28 am" src="https://cloud.githubusercontent.com/assets/10722197/23980031/2654f622-0a38-11e7-892c-9b5961e34fe5.png">
<img width="386" alt="screen shot 2017-03-16 at 11 02 51 am" src="https://cloud.githubusercontent.com/assets/10722197/23980033/28262322-0a38-11e7-89ac-8caeaefec380.png">

**Comment by TayKangSheng** [comment]
Then you should authenticate user before [:show, :edit, :update, :destroy]

<img width="745" alt="screen shot 2017-03-16 at 11 23 44 am" src="https://cloud.githubusercontent.com/assets/10722197/23980529/24f72ad6-0a3b-11e7-8ce6-1593b16634e4.png">

**Comment by wshimei** [comment]
should be ok now with latest update.
