### ISSUE TITLE
Error when requesting service

### ISSUE THREAD

**Issue by TayKangSheng** [wdi-sg/project-3-das#15]
Something went wrong...

<img width="494" alt="screen shot 2017-03-16 at 11 04 35 am" src="https://cloud.githubusercontent.com/assets/10722197/23980076/6d676acc-0a38-11e7-9b12-8f151f0a234b.png">
<img width="816" alt="screen shot 2017-03-16 at 11 04 40 am" src="https://cloud.githubusercontent.com/assets/10722197/23980077/6ede404c-0a38-11e7-8e9f-af9e1d7f7173.png">

**Comment by TayKangSheng** [comment]
Now request invoice does not work.. :(

<img width="673" alt="screen shot 2017-03-16 at 11 05 43 am" src="https://cloud.githubusercontent.com/assets/10722197/23980097/9079b376-0a38-11e7-8553-a74354b2979c.png">

**Comment by wshimei** [comment]
why so sad.
